apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: cdc-monitoring
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:latest
        ports:
        - containerPort: 9000
        env:
        - name: KAFKA_BROKERCONNECT
          valueFrom:
            configMapKeyRef:
              name: kafdrop-config
              key: kafka.brokers
        - name: JVM_OPTS
          value: "-Xms256M -Xmx1G"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"
        - name: CMD_ARGS
          valueFrom:
            configMapKeyRef:
              name: kafdrop-config
              key: kafdrop.args
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 15